"""Build the per-model existence Appendix table (Table~\\ref{tab:existence_per_model}).

Reads ``paper/figures/rq_stats/rq_existence.csv`` (one row per
(model, event, trait) cell with the ``pct_personas_moved`` rate and a
``bucket`` indicator separating cells with a definite human prior
(``prior``) from off-target cells with no prior (``off_target``)) and
emits a LaTeX table summarising, for each model, the *within-model*
shape of the two ``pct_moved`` distributions.

We deliberately do **not** average across persona/event/trait axes:
the cell rate ``pct_moved`` already lives at the (model, event, trait)
granularity. The summary statistics reported per model are
distribution-shape descriptors (P25, P50, P75 and the high-tail mass
``pct_cells_above_0.6``) over its own 27 prior cells and 28 off-target
cells. The gap ``\\Delta P_{50}`` keeps the within-model median visible
as a single number so a reviewer can verify the alternating-sign
pattern described in \\S4.1.

Usage::

    python scripts/build_existence_table.py \\
        --csv paper/figures/rq_stats/rq_existence.csv \\
        --out paper/figures/rq_stats/per_model_existence.tex
"""

from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path
from statistics import quantiles, median


SHORT_LABEL = {
    "gpt-5.3-chat": "GPT-5.3-chat",
    "gpt-4.1-mini": "GPT-4.1-mini",
    "claude-sonnet-4.6": "Claude-Sonnet-4.6",
    "claude-haiku-4.5": "Claude-Haiku-4.5",
    "gemini-3-flash": "Gemini-3-flash",
    "deepseek-v4-pro": "DeepSeek-V4-Pro",
    "doubao-seed-2.0-pro": "Doubao-Seed-2.0-Pro",
    "mimo-v2.5-pro": "MiMo-V2.5-Pro",
    "sf-qwen3-235b": "Qwen3-235B",
    "sf-glm-4.6": "GLM-4.6",
    "sf-kimi-k2-0905": "Kimi-K2-0905",
}


# Order of rows in the table. Matches the leaderboard order used elsewhere
# in the paper (BFI-Adapt descending); models not in this list are appended.
MODEL_ORDER = [
    "gemini-3-flash",
    "sf-glm-4.6",
    "sf-qwen3-235b",
    "claude-haiku-4.5",
    "sf-kimi-k2-0905",
    "doubao-seed-2.0-pro",
    "claude-sonnet-4.6",
    "gpt-4.1-mini",
    "gpt-5.3-chat",
    "deepseek-v4-pro",
    "mimo-v2.5-pro",
]


def _quartiles(xs):
    """Return (P25, P50, P75). Falls back gracefully for short samples."""
    if not xs:
        return float("nan"), float("nan"), float("nan")
    xs_sorted = sorted(xs)
    if len(xs_sorted) < 4:
        m = median(xs_sorted)
        return xs_sorted[0], m, xs_sorted[-1]
    q1, q2, q3 = quantiles(xs_sorted, n=4, method="inclusive")
    return q1, q2, q3


def load_cells(csv_path: Path):
    """Return dict[model][bucket] -> list of pct_personas_moved."""
    by_model = defaultdict(lambda: defaultdict(list))
    with csv_path.open() as f:
        for row in csv.DictReader(f):
            model = row["model"]
            bucket = row["bucket"]
            pct = float(row["pct_personas_moved"])
            by_model[model][bucket].append(pct)
    return by_model


def fmt(x):
    return f"{x:.2f}" if x == x else "---"  # NaN check


def build_table(by_model):
    """Emit a two-column-wide LaTeX table summarising prior vs off-target shape."""
    # Order models deterministically.
    ordered = [m for m in MODEL_ORDER if m in by_model]
    ordered += [m for m in by_model if m not in MODEL_ORDER]

    lines = []
    lines.append(r"% Auto-generated by scripts/build_existence_table.py "
                 r"-- DO NOT EDIT")
    lines.append(r"\begin{table*}[t]")
    lines.append(r"\centering\small")
    lines.append(r"\caption{Per-model shape of $\mathrm{pct}_{\text{moved}}$ "
                 r"distributions for the 27 definite-direction pairs and 28 "
                 r"no-definite-direction pairs (Section~\ref{sec:rq1}). We report quartiles "
                 r"($P_{25}, P_{50}, P_{75}$) of $\mathrm{pct}_{\text{moved}}$ within "
                 r"each bucket together with the high-tail mass "
                 r"$\mathrm{Hi}\%=$ fraction of pairs with "
                 r"$\mathrm{pct}_{\text{moved}}{>}0.6$. The last column gives "
                 r"the definite-direction minus no-definite-direction gap in within-model medians "
                 r"$\Delta P_{50}=P_{50}^{\text{dir}}-P_{50}^{\text{no-dir}}$. "
                 r"Gaps are uniformly $|\Delta P_{50}|\!\leq\!0.045$ and "
                 r"alternate sign across models, supporting the conclusion "
                 r"that existence of movement is decoupled from whether human "
                 r"evidence specifies a direction.}")
    lines.append(r"\label{tab:existence_per_model}")
    lines.append(r"\begin{tabular*}{\textwidth}"
                 r"{l@{\extracolsep{\fill}}rrrrrrrrr}")
    lines.append(r"\toprule")
    lines.append(r" & \multicolumn{4}{c}{Definite direction (27)} "
                 r"& \multicolumn{4}{c}{No definite direction (28)} & \\")
    lines.append(r"\cmidrule(lr){2-5}\cmidrule(lr){6-9}")
    lines.append(r"Model & $P_{25}$ & $P_{50}$ & $P_{75}$ & $\mathrm{Hi}\%$ "
                 r"& $P_{25}$ & $P_{50}$ & $P_{75}$ & $\mathrm{Hi}\%$ "
                 r"& $\Delta P_{50}$ \\")
    lines.append(r"\midrule")

    for m in ordered:
        prior = by_model[m].get("prior", [])
        off = by_model[m].get("off_target", [])
        p25p, p50p, p75p = _quartiles(prior)
        p25o, p50o, p75o = _quartiles(off)
        hi_p = sum(1 for x in prior if x > 0.6) / len(prior) if prior else float("nan")
        hi_o = sum(1 for x in off if x > 0.6) / len(off) if off else float("nan")
        gap = p50p - p50o if prior and off else float("nan")
        lines.append(
            f"{SHORT_LABEL.get(m, m)} & "
            f"{fmt(p25p)} & {fmt(p50p)} & {fmt(p75p)} & {fmt(hi_p)} & "
            f"{fmt(p25o)} & {fmt(p50o)} & {fmt(p75o)} & {fmt(hi_o)} & "
            f"{fmt(gap)} \\\\"
        )

    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular*}")
    lines.append(r"\end{table*}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", type=Path,
                    default=Path("paper/figures/rq_stats/rq_existence.csv"))
    ap.add_argument("--out", type=Path,
                    default=Path("paper/figures/rq_stats/per_model_existence.tex"))
    args = ap.parse_args()

    by_model = load_cells(args.csv)
    tex = build_table(by_model)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(tex)
    print(f"Wrote {args.out} ({len(by_model)} models)")


if __name__ == "__main__":
    main()
